name: shivsneh
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  transparent_image: ^2.0.1
  counter_button: ^1.0.1
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  firebase_storage: ^11.3.1
  image_picker: ^1.0.4
  cloud_firestore: ^4.11.0
  uuid: ^4.1.0
#  location: ^5.0.3
#  http: ^1.1.0
#  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/icon/
    - assets/images/

flutter_launcher_icons:
  image_path: "./assets/icon/app-icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
